//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TISS_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleContent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArticleContent()
        {
            this.MessageBoard = new HashSet<MessageBoard>();
            this.Documents = new HashSet<Documents>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string ContentBody { get; set; }
        public string ContentType { get; set; }
        public byte[] ImageContent { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public string Hashtags { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public string TargetView { get; set; }
        public string EncryptedUrl { get; set; }
        public Nullable<int> ClickCount { get; set; }
        public Nullable<int> ContentTypeId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageBoard> MessageBoard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documents> Documents { get; set; }
    }
}
