//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TISS_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenderEqualityDetails
    {
        public int Id { get; set; }
        public Nullable<int> GenderEqualityId { get; set; }
        public string URL { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string ImagePath { get; set; }
        public string ImageFileName { get; set; }
        public Nullable<int> ImageSize { get; set; }
        public string ImageType { get; set; }
        public string AdditionalInfo { get; set; }
    
        public virtual GenderEquality GenderEquality { get; set; }
    }
}
