//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TISS_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageBoard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MessageBoard()
        {
            this.ReplyMessage = new HashSet<ReplyMessage>();
        }
    
        public int Id { get; set; }
        public int ArticleId { get; set; }
        public string UserName { get; set; }
        public string CommentText { get; set; }
        public System.DateTime CommentDate { get; set; }
        public bool IsApproved { get; set; }
        public bool IsEditor { get; set; }
    
        public virtual ArticleContent ArticleContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReplyMessage> ReplyMessage { get; set; }
    }
}
