//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TISS_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TISS_WebEntities : DbContext
    {
        public TISS_WebEntities()
            : base("name=TISS_WebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Permissions> Permissions { get; set; }
        public virtual DbSet<RolePermissions> RolePermissions { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<AboutPageContent> AboutPageContent { get; set; }
        public virtual DbSet<AnnouncementPageContent> AnnouncementPageContent { get; set; }
        public virtual DbSet<BODPageContent> BODPageContent { get; set; }
        public virtual DbSet<BudgetPageContent> BudgetPageContent { get; set; }
        public virtual DbSet<CEOPageContent> CEOPageContent { get; set; }
        public virtual DbSet<DownloadPageContent> DownloadPageContent { get; set; }
        public virtual DbSet<GenderEqualityPageContent> GenderEqualityPageContent { get; set; }
        public virtual DbSet<GovernmentWebsitePageContent> GovernmentWebsitePageContent { get; set; }
        public virtual DbSet<HomePageContent> HomePageContent { get; set; }
        public virtual DbSet<InstitutePageContent> InstitutePageContent { get; set; }
        public virtual DbSet<MissionPageContent> MissionPageContent { get; set; }
        public virtual DbSet<ObjectivesPageContent> ObjectivesPageContent { get; set; }
        public virtual DbSet<OrganizationPageContent> OrganizationPageContent { get; set; }
        public virtual DbSet<OtherPageContent> OtherPageContent { get; set; }
        public virtual DbSet<PlanPageContent> PlanPageContent { get; set; }
        public virtual DbSet<PressPageContent> PressPageContent { get; set; }
        public virtual DbSet<ProcedurePageContent> ProcedurePageContent { get; set; }
        public virtual DbSet<Public_InfoPageContent> Public_InfoPageContent { get; set; }
        public virtual DbSet<PurchasePageContent> PurchasePageContent { get; set; }
        public virtual DbSet<RecruitPageContent> RecruitPageContent { get; set; }
        public virtual DbSet<RegulationPageContent> RegulationPageContent { get; set; }
        public virtual DbSet<ResearchPageContent> ResearchPageContent { get; set; }
        public virtual DbSet<ResearchProjectPageContent> ResearchProjectPageContent { get; set; }
        public virtual DbSet<SportMedicinePageContent> SportMedicinePageContent { get; set; }
        public virtual DbSet<SportSciencePageContent> SportSciencePageContent { get; set; }
        public virtual DbSet<SportTechPageContent> SportTechPageContent { get; set; }
        public virtual DbSet<UnitsPageContent> UnitsPageContent { get; set; }
        public virtual DbSet<VideoPageContent> VideoPageContent { get; set; }
        public virtual DbSet<PhysicalTrainingPageContent> PhysicalTrainingPageContent { get; set; }
        public virtual DbSet<SportsNutritionPageContent> SportsNutritionPageContent { get; set; }
        public virtual DbSet<SportsPhysiologyPageContent> SportsPhysiologyPageContent { get; set; }
        public virtual DbSet<SportsPsychologyPageContent> SportsPsychologyPageContent { get; set; }
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<ArticleClickCount> ArticleClickCount { get; set; }
    }
}
